/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AllAccountsResponse, Uint128, Expiration, Timestamp, Uint64, AllAllowancesResponse, AllowanceInfo, AllowanceResponse, BalanceResponse, Cw20ExecuteMsg, Binary, Logo, EmbeddedLogo, Cw20QueryMsg, Cw20ReceiveMsg, DownloadLogoResponse, LogoInfo, Addr, MarketingInfoResponse, MinterResponse, TokenInfoResponse } from "./Cw20.types";